<?php

namespace Database\Seeders;

use App\Actions\Audit\RecordAuditEvent;
use App\Enums\AuditAction;
use App\Enums\MediaStatus;
use App\Jobs\GenerateImageVariants;
use App\Models\MediaAsset;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Geometry\Factories\EllipseFactory;
use Intervention\Image\Geometry\Factories\RectangleFactory;
use Intervention\Image\ImageManager;

/**
 * Local sample DAM assets with real files generated offline with GD: images
 * of different proportions and formats, a neutral logo that suits every
 * accent preset, two PDFs, alt texts (some missing),
 * one asset still in quarantine and one rejected.
 *
 * Demo data only: the seeder sets the scan status directly instead of
 * running ClamAV, because the files are generated here and never come from
 * a user. Production uploads always go through StoreMediaAsset and the scan.
 * Public variants of clean images are generated by the regular queued
 * {@see GenerateImageVariants} job. Idempotent: assets are keyed by a fixed
 * UUID; an existing one is left untouched.
 */
class DemoMediaSeeder extends Seeder
{
    /**
     * @var array<string, array{uuid: string, name: string, mime: string, width?: int, height?: int, color?: string, alt: string|null, status: MediaStatus}>
     */
    public const array ASSETS = [
        'landscape' => ['uuid' => 'de000000-0000-4000-a000-000000000001', 'name' => 'krajobraz-mazury.jpg', 'mime' => 'image/jpeg', 'width' => 1600, 'height' => 900, 'color' => '2563eb', 'alt' => 'Jezioro na Mazurach o zachodzie słońca', 'status' => MediaStatus::Clean],
        'portrait' => ['uuid' => 'de000000-0000-4000-a000-000000000002', 'name' => 'portrait-editor.jpg', 'mime' => 'image/jpeg', 'width' => 900, 'height' => 1350, 'color' => 'db2777', 'alt' => 'Portrait of the editor in the office', 'status' => MediaStatus::Clean],
        'square' => ['uuid' => 'de000000-0000-4000-a000-000000000003', 'name' => 'logo-kwadrat.png', 'mime' => 'image/png', 'width' => 1200, 'height' => 1200, 'color' => '16a34a', 'alt' => 'Kwadratowe logo z literą S', 'status' => MediaStatus::Clean],
        'panorama' => ['uuid' => 'de000000-0000-4000-a000-000000000004', 'name' => 'panorama-tatry-zima-bardzo-dluga-nazwa-pliku-do-sprawdzenia-zawijania.jpg', 'mime' => 'image/jpeg', 'width' => 2400, 'height' => 800, 'color' => '0891b2', 'alt' => 'Panorama Tatr zimą widziana z Gubałówki: ośnieżone szczyty, błękitne niebo i drewniane chaty na pierwszym planie, które pokazują, jak długi tekst alternatywny wygląda w panelu', 'status' => MediaStatus::Clean],
        'small' => ['uuid' => 'de000000-0000-4000-a000-000000000005', 'name' => 'icon-small.png', 'mime' => 'image/png', 'width' => 320, 'height' => 240, 'color' => 'ea580c', 'alt' => null, 'status' => MediaStatus::Clean],
        'wide' => ['uuid' => 'de000000-0000-4000-a000-000000000006', 'name' => 'event-hall.jpg', 'mime' => 'image/jpeg', 'width' => 1920, 'height' => 1080, 'color' => '7c3aed', 'alt' => 'Conference hall before the event', 'status' => MediaStatus::Clean],
        'team' => ['uuid' => 'de000000-0000-4000-a000-000000000007', 'name' => 'zespół-2026.jpg', 'mime' => 'image/jpeg', 'width' => 1400, 'height' => 933, 'color' => 'ca8a04', 'alt' => 'Zespół na schodach biura w Łodzi', 'status' => MediaStatus::Clean],
        'webp' => ['uuid' => 'de000000-0000-4000-a000-000000000008', 'name' => 'tips-cover.webp', 'mime' => 'image/webp', 'width' => 1200, 'height' => 800, 'color' => '0f766e', 'alt' => 'Notebook with handwritten tips', 'status' => MediaStatus::Clean],
        'tall' => ['uuid' => 'de000000-0000-4000-a000-000000000009', 'name' => 'infografika.png', 'mime' => 'image/png', 'width' => 600, 'height' => 1600, 'color' => 'be123c', 'alt' => 'Infografika: pięć kroków do szybszej strony', 'status' => MediaStatus::Clean],
        'no-alt' => ['uuid' => 'de000000-0000-4000-a000-000000000010', 'name' => 'IMG_2048.jpg', 'mime' => 'image/jpeg', 'width' => 1024, 'height' => 768, 'color' => '475569', 'alt' => null, 'status' => MediaStatus::Clean],
        'pending' => ['uuid' => 'de000000-0000-4000-a000-000000000011', 'name' => 'nowe-zdjęcie.jpg', 'mime' => 'image/jpeg', 'width' => 800, 'height' => 600, 'color' => '64748b', 'alt' => null, 'status' => MediaStatus::Quarantine],
        'rejected' => ['uuid' => 'de000000-0000-4000-a000-000000000012', 'name' => 'faktura-podejrzana.jpg', 'mime' => 'image/jpeg', 'width' => 800, 'height' => 600, 'color' => '991b1b', 'alt' => null, 'status' => MediaStatus::Rejected],
        'logo' => ['uuid' => 'de000000-0000-4000-a000-000000000015', 'name' => 'logo-pracownia.png', 'mime' => 'image/png', 'width' => 512, 'height' => 512, 'color' => '27272a', 'alt' => 'Logo Pracowni Nowak', 'status' => MediaStatus::Clean],
        'office' => ['uuid' => 'de000000-0000-4000-a000-000000000016', 'name' => 'biuro-piotrkowska.jpg', 'mime' => 'image/jpeg', 'width' => 1600, 'height' => 1067, 'color' => '57534e', 'alt' => 'Biuro pracowni przy ulicy Piotrkowskiej', 'status' => MediaStatus::Clean],
        'workshop' => ['uuid' => 'de000000-0000-4000-a000-000000000017', 'name' => 'workshop-laptops.jpg', 'mime' => 'image/jpeg', 'width' => 1600, 'height' => 900, 'color' => '1e3a8a', 'alt' => 'Laptops on a table during a workshop', 'status' => MediaStatus::Clean],
        'pdf' => ['uuid' => 'de000000-0000-4000-a000-000000000013', 'name' => 'cennik-2026.pdf', 'mime' => 'application/pdf', 'alt' => 'Cennik usług 2026', 'status' => MediaStatus::Clean],
        'pdf-pending' => ['uuid' => 'de000000-0000-4000-a000-000000000014', 'name' => 'terms-and-conditions.pdf', 'mime' => 'application/pdf', 'alt' => null, 'status' => MediaStatus::Quarantine],
    ];

    public function run(RecordAuditEvent $audit): void
    {
        $owner = User::query()->where('email', DemoContent::USER_EMAIL)->first();
        $disk = (string) config('media.disk');

        foreach (self::ASSETS as $definition) {
            if (MediaAsset::query()->where('uuid', $definition['uuid'])->exists()) {
                continue;
            }

            $bytes = $this->fileContents($definition);
            $extension = match ($definition['mime']) {
                'image/png' => 'png',
                'image/webp' => 'webp',
                'application/pdf' => 'pdf',
                default => 'jpg',
            };
            $path = "{$definition['uuid']}/original.{$extension}";
            $status = $definition['status'];

            if ($status !== MediaStatus::Rejected) {
                Storage::disk($disk)->put($path, $bytes);
            }

            $asset = DB::transaction(function () use ($definition, $owner, $disk, $path, $bytes, $status, $audit): MediaAsset {
                $asset = new MediaAsset;
                $asset->forceFill([
                    'uuid' => $definition['uuid'],
                    'owner_id' => $owner?->id,
                    'disk' => $disk,
                    'path' => $path,
                    'original_name' => $definition['name'],
                    'mime' => $definition['mime'],
                    'size' => strlen($bytes),
                    'width' => $definition['width'] ?? null,
                    'height' => $definition['height'] ?? null,
                    'checksum' => hash('sha256', $bytes),
                    'status' => $status,
                    'scan_error' => $status === MediaStatus::Rejected ? 'Malware detected: Eicar-Test-Signature' : null,
                    'alt' => $definition['alt'],
                ])->save();

                $audit->handle(AuditAction::MediaUploaded, $asset, $owner, [
                    'original_name' => RecordAuditEvent::change(null, $definition['name']),
                    'mime' => RecordAuditEvent::change(null, $definition['mime']),
                    'status' => RecordAuditEvent::change(null, MediaStatus::Quarantine->value),
                ]);

                if ($status !== MediaStatus::Quarantine) {
                    $audit->handle(
                        $status === MediaStatus::Clean ? AuditAction::MediaCleaned : AuditAction::MediaRejected,
                        $asset,
                        null,
                        ['status' => RecordAuditEvent::change(MediaStatus::Quarantine->value, $status->value)],
                    );
                }

                return $asset;
            });

            if ($status === MediaStatus::Clean && $asset->isImage()) {
                GenerateImageVariants::dispatch($asset->id);
            }
        }
    }

    /**
     * Id of a seeded asset by its key in self::ASSETS, if it exists.
     */
    public static function assetId(string $key): ?int
    {
        $id = MediaAsset::query()->where('uuid', self::ASSETS[$key]['uuid'])->value('id');

        return is_int($id) ? $id : null;
    }

    /**
     * @param  array{uuid: string, name: string, mime: string, width?: int, height?: int, color?: string, alt: string|null, status: MediaStatus}  $definition
     */
    private function fileContents(array $definition): string
    {
        if ($definition['mime'] === 'application/pdf') {
            return self::pdf($definition['name']);
        }

        $width = $definition['width'] ?? 800;
        $height = $definition['height'] ?? 600;
        $image = ImageManager::gd()->create($width, $height)->fill($definition['color'] ?? '64748b');

        $image->drawEllipse(intdiv($width, 3), intdiv($height, 2), function (EllipseFactory $ellipse) use ($width, $height): void {
            $ellipse->size(intdiv(min($width, $height) * 3, 4), intdiv(min($width, $height) * 3, 4));
            $ellipse->background('ffffff66');
        });
        $image->drawRectangle(intdiv($width, 2), intdiv($height, 4), function (RectangleFactory $rectangle) use ($width, $height): void {
            $rectangle->size(intdiv($width, 3), intdiv($height, 2));
            $rectangle->background('00000033');
        });

        return match ($definition['mime']) {
            'image/png' => $image->toPng()->toString(),
            'image/webp' => $image->toWebp(80)->toString(),
            default => $image->toJpeg(80)->toString(),
        };
    }

    /**
     * A minimal valid one-page PDF with the file name as its only text.
     */
    private static function pdf(string $title): string
    {
        $text = preg_replace('/[^A-Za-z0-9 .\-]/', '', $title);
        $stream = "BT /F1 24 Tf 72 720 Td ({$text}) Tj ET";
        $objects = [
            '<< /Type /Catalog /Pages 2 0 R >>',
            '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
            '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
            '<< /Length '.strlen($stream)." >>\nstream\n{$stream}\nendstream",
            '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
        ];

        $pdf = "%PDF-1.4\n";
        $offsets = [];

        foreach ($objects as $index => $object) {
            $offsets[] = strlen($pdf);
            $pdf .= ($index + 1)." 0 obj\n{$object}\nendobj\n";
        }

        $xref = strlen($pdf);
        $pdf .= 'xref'."\n0 ".(count($objects) + 1)."\n0000000000 65535 f \n";

        foreach ($offsets as $offset) {
            $pdf .= sprintf("%010d 00000 n \n", $offset);
        }

        return $pdf.'trailer'."\n<< /Size ".(count($objects) + 1)." /Root 1 0 R >>\nstartxref\n{$xref}\n%%EOF\n";
    }
}
