import { router, useForm } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import {
    Alert,
    Button,
    ConfirmDialog,
    ConflictDialog,
    PageHeader,
    ResourceForm,
    Stack,
} from '@/design-system/primitives';
import { useTranslation } from '@/i18n';
import { destroy, edit, index, store, update } from '@/routes/admin/faqs';

type EditorProps = App.Data.Admin.Faqs.FaqEditorData;
type RecordData = App.Data.Admin.Faqs.FaqFormData;

/** Editable form state; keys are the request field names. */
type FormValues = {
    question: string;
    answer: string;
    position: string;
    published: boolean;
};

const FIELD_NAMES: string[] = ['question', 'answer', 'position', 'published'];

function toValues(record: RecordData): FormValues {
    return {
        question: record.question ?? '',
        answer: record.answer ?? '',
        position: record.position === null ? '' : String(record.position),
        published: record.published,
    };
}

export type FaqFormProps = {
    editor: EditorProps;
};

/**
 * Shared create/edit screen of a faq: one `ResourceForm`,
 * optimistic-lock conflict handling and deletion (generated by
 * `app:make-resource`).
 */
export function FaqForm({ editor }: FaqFormProps) {
    const record = editor.faq;
    const recordId = record.id;
    const { can } = editor;
    const { t } = useTranslation();
    const form = useForm<FormValues>(toValues(record));
    const [isConflictOpen, setIsConflictOpen] = useState(false);
    const [isDeleteOpen, setIsDeleteOpen] = useState(false);
    const [isDeleting, setIsDeleting] = useState(false);

    const errors = form.errors as Partial<Record<string, string>>;
    /** Errors that no field renders inline (e.g. `updated_at`). */
    const generalErrors = Object.keys(errors)
        .filter((key) => key !== 'conflict' && !FIELD_NAMES.includes(key))
        .map((key) => errors[key] ?? '')
        .filter((message) => message !== '');

    useEffect(() => {
        if (!form.isDirty) {
            return;
        }

        return router.on('before', (event) => {
            const visit = event.detail.visit;

            if (
                visit.method !== 'get' ||
                visit.url.pathname === window.location.pathname
            ) {
                return;
            }

            if (!window.confirm(t('admin.faqs.unsavedChanges'))) {
                event.preventDefault();
            }
        });
    }, [form.isDirty, t]);

    function submit() {
        form.transform((data) => ({
            ...data,
            ...(recordId !== null
                ? { updated_at: record.updatedAt ?? '' }
                : {}),
        }));

        const options = {
            preserveScroll: true,
            onSuccess: () => form.setDefaults(),
            onError: (received: Partial<Record<string, string>>) => {
                if (received.conflict) {
                    setIsConflictOpen(true);
                }
            },
        };

        if (recordId === null) {
            form.submit(store(), options);
        } else {
            form.submit(update(recordId), options);
        }
    }

    function reloadLatest() {
        if (recordId === null) {
            return;
        }

        setIsConflictOpen(false);
        router.visit(edit.url(recordId), { preserveState: false });
    }

    function confirmDelete() {
        if (recordId === null) {
            return;
        }

        setIsDeleting(true);
        router.delete(destroy.url(recordId), {
            onFinish: () => setIsDeleting(false),
        });
    }

    return (
        <Stack gap="relaxed">
            <PageHeader
                title={
                    recordId === null
                        ? t('admin.faqs.createTitle')
                        : t('admin.faqs.editTitle')
                }
                description={t('admin.faqs.description')}
                actions={
                    recordId !== null && can.delete ? (
                        <Button
                            variant="destructive"
                            onClick={() => setIsDeleteOpen(true)}
                        >
                            {t('admin.faqs.delete')}
                        </Button>
                    ) : undefined
                }
            />

            {generalErrors.length > 0 && (
                <Alert
                    tone="danger"
                    title={t('admin.faqs.errorSummaryTitle')}
                    description={generalErrors.join(' ')}
                />
            )}

            <ResourceForm<FormValues>
                values={form.data}
                errors={errors}
                onChange={(name, value) =>
                    form.setData((data) => ({ ...data, [name]: value }))
                }
                onSubmit={submit}
                isPending={form.processing}
                cancelHref={index()}
                labels={{
                    submit: form.processing
                        ? t('admin.faqs.saving')
                        : t('admin.faqs.save'),
                    cancel: t('admin.faqs.cancel'),
                    errorSummaryTitle: t('admin.faqs.errorSummaryTitle'),
                }}
                sections={[
                    {
                        id: 'details',
                        title: t('admin.faqs.detailsTitle'),
                        fields: [
                            {
                                type: 'text',
                                name: 'question',
                                label: t('admin.faqs.fields.question'),
                                required: true,
                            },
                            {
                                type: 'textarea',
                                name: 'answer',
                                label: t('admin.faqs.fields.answer'),
                                rows: 5,
                                required: true,
                            },
                            {
                                type: 'number',
                                name: 'position',
                                label: t('admin.faqs.fields.position'),
                                step: 1,
                            },
                            {
                                type: 'switch',
                                name: 'published',
                                label: t('admin.faqs.fields.published'),
                            },
                        ],
                    },
                ]}
            />

            {recordId !== null && (
                <ConflictDialog
                    open={isConflictOpen}
                    onOpenChange={setIsConflictOpen}
                    title={t('admin.faqs.conflictTitle')}
                    description={t('admin.faqs.conflictDescription')}
                    reloadLabel={t('admin.faqs.conflictReload')}
                    onReload={reloadLatest}
                    overwriteLabel={t('admin.faqs.cancel')}
                    onOverwrite={() => setIsConflictOpen(false)}
                />
            )}

            {recordId !== null && can.delete && (
                <ConfirmDialog
                    open={isDeleteOpen}
                    onOpenChange={setIsDeleteOpen}
                    title={t('admin.faqs.deleteTitle')}
                    description={t('admin.faqs.deleteDescription')}
                    confirmLabel={t('admin.faqs.deleteConfirm')}
                    cancelLabel={t('admin.faqs.cancel')}
                    closeLabel={t('actions.close')}
                    tone="destructive"
                    isPending={isDeleting}
                    onConfirm={confirmDelete}
                />
            )}
        </Stack>
    );
}
