import { Head, router, usePage } from '@inertiajs/react';
import { Pencil, Trash2 } from 'lucide-react';
import { useState } from 'react';
import {
    Badge,
    Button,
    ConfirmDialog,
    Link,
    ResourceTable,
} from '@/design-system/primitives';
import { useTranslation } from '@/i18n';
import { index as adminIndex } from '@/routes/admin';
import { create, destroy, edit, index } from '@/routes/admin/faqs';

type Row = App.Data.Admin.Faqs.FaqListItemData;
type IndexProps = App.Data.Admin.Faqs.FaqIndexData;

/**
 * Admin list of faqs (generated by `app:make-resource`).
 */
export default function AdminFaqsIndex() {
    const { items, pagination, filters, can } = usePage<IndexProps>().props;
    const { t, formatDate } = useTranslation();
    const [rowToDelete, setRowToDelete] = useState<Row | null>(null);
    const [isDeleting, setIsDeleting] = useState(false);

    const rowTitle = (row: Row) =>
        row.question || t('admin.faqs.untitled', { id: row.id });

    function confirmDelete() {
        if (!rowToDelete) {
            return;
        }

        setIsDeleting(true);
        router.delete(destroy.url(rowToDelete.id), {
            preserveScroll: true,
            onSuccess: () => setRowToDelete(null),
            onFinish: () => setIsDeleting(false),
        });
    }

    return (
        <>
            <Head title={t('admin.faqs.title')} />

            <ResourceTable<Row>
                url={index()}
                header={{
                    title: t('admin.faqs.title'),
                    description: t('admin.faqs.description'),
                    actions: can.create ? (
                        <Button href={create()}>
                            {t('admin.faqs.create')}
                        </Button>
                    ) : undefined,
                }}
                rows={items}
                rowKey={(row) => row.id}
                pagination={pagination}
                filters={filters}
                searchable
                labels={{
                    caption: t('admin.faqs.tableCaption'),
                    searchLabel: t('admin.faqs.searchLabel'),
                    searchPlaceholder: t('admin.faqs.searchPlaceholder'),
                    searchClear: t('admin.faqs.searchClear'),
                    clearFilters: t('admin.faqs.clearFilters'),
                    emptyTitle: t('admin.faqs.emptyTitle'),
                    emptyDescription: t('admin.faqs.emptyDescription'),
                    noResultsTitle: t('admin.faqs.emptyFilteredTitle'),
                    noResultsDescription: t(
                        'admin.faqs.emptyFilteredDescription',
                    ),
                    errorTitle: t('admin.faqs.errorTitle'),
                    errorRetry: t('admin.faqs.errorRetry'),
                    previousPage: t('admin.faqs.previousPage'),
                    nextPage: t('admin.faqs.nextPage'),
                    paginationSummary: (range) =>
                        t('admin.faqs.paginationSummary', range),
                }}
                filterFields={[
                    {
                        name: 'published',
                        label: t('admin.faqs.fields.published'),
                        defaultValue: 'all',
                        options: [
                            { value: 'all', label: t('admin.faqs.filterAll') },
                            { value: 'yes', label: t('admin.faqs.yes') },
                            { value: 'no', label: t('admin.faqs.no') },
                        ],
                    },
                ]}
                columns={[
                    {
                        key: 'question',
                        label: t('admin.faqs.fields.question'),
                        sortable: true,
                        render: (row) => (
                            <Link href={edit(row.id)} tone="primary">
                                {rowTitle(row)}
                            </Link>
                        ),
                    },
                    {
                        key: 'position',
                        label: t('admin.faqs.fields.position'),
                        sortable: true,
                        render: (row) => row.position ?? '—',
                    },
                    {
                        key: 'published',
                        label: t('admin.faqs.fields.published'),
                        render: (row) => (
                            <Badge tone={row.published ? 'success' : 'neutral'}>
                                {row.published
                                    ? t('admin.faqs.yes')
                                    : t('admin.faqs.no')}
                            </Badge>
                        ),
                    },
                    {
                        key: 'created_at',
                        label: t('admin.faqs.columnCreatedAt'),
                        sortable: true,
                        render: (row) =>
                            row.createdAt ? formatDate(row.createdAt) : '—',
                    },
                ]}
                rowActions={{
                    label: (row) =>
                        t('admin.faqs.rowActionsLabel', {
                            title: rowTitle(row),
                        }),
                    items: (row) => [
                        {
                            id: 'edit',
                            label: t('admin.faqs.actionEdit'),
                            icon: Pencil,
                            onSelect: () => router.visit(edit.url(row.id)),
                        },
                        ...(can.delete
                            ? [
                                  {
                                      id: 'delete',
                                      label: t('admin.faqs.actionDelete'),
                                      icon: Trash2,
                                      tone: 'destructive' as const,
                                      onSelect: () => setRowToDelete(row),
                                  },
                              ]
                            : []),
                    ],
                }}
            />

            <ConfirmDialog
                open={rowToDelete !== null}
                onOpenChange={(open) => {
                    if (!open) {
                        setRowToDelete(null);
                    }
                }}
                title={t('admin.faqs.deleteTitle')}
                description={t('admin.faqs.deleteDescription')}
                confirmLabel={t('admin.faqs.deleteConfirm')}
                cancelLabel={t('admin.faqs.cancel')}
                closeLabel={t('actions.close')}
                tone="destructive"
                isPending={isDeleting}
                onConfirm={confirmDelete}
            />
        </>
    );
}

AdminFaqsIndex.layout = {
    breadcrumbs: [
        {
            title: 'admin.dashboard',
            href: adminIndex(),
        },
        {
            title: 'admin.faqs.title',
            href: index(),
        },
    ],
};
