export type QrCodeProps = {
    /** SVG markup generated by the backend (e.g. Fortify), never user input. */
    svg: string;
    /** Translated accessible name, e.g. "QR code for your authenticator app". */
    label: string;
    className?: never;
    style?: never;
};

/**
 * Scannable QR code. Scanners need dark modules on a light quiet zone, so the
 * frame stays white in both themes: a functional colour, not a theme token.
 * The SVG renders as an image, so its markup never enters the DOM.
 */
export function QrCode({ svg, label }: QrCodeProps) {
    return (
        <div className="mx-auto w-full max-w-56 rounded-lg bg-white p-4">
            <img
                src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`}
                alt={label}
                width={192}
                height={192}
                className="block aspect-square h-auto w-full"
            />
        </div>
    );
}
